version: '3.8'

services:
  github-runner:
    image: myoung34/github-runner:latest
    container_name: quickbite-runner
    environment:
      REPO_URL: "https://github.com/daoquan2k3/md5_ss8"
      RUNNER_NAME: "quickbite-server"
      RUNNER_TOKEN: "BZK37QZUA3JW7UKSTJUEOELKN4QEK"
      RUNNER_LABELS: "quickbite-runner"
      RUNNER_WORKDIR: "/tmp/runner/work"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/runner:/tmp/runner
    restart: always